[package]
name = "desktop"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# ライブラリの設定
[lib]
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

# ビルド用の依存関係
[build-dependencies]
tauri-build = { version = "2", features = [] }
cc = "1"

# アプリの依存関係
[dependencies]
tauri = { version = "2.0.0", features = ["image-png", "wry"] }
tauri-plugin-opener = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Windowsの入力操作
[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
